<?php

namespace Abc\Scheduler;

interface ExtensionInterface extends StartExtensionInterface, InitLoggerExtensionInterface, PreIterateProvidersExtensionInterface, PreProvideSchedulesExtensionInterface, CheckScheduleExtensionInterface, PreProcessScheduleExtensionInterface, ScheduleProcessedExtensionInterface, EndExtensionInterface
{
}
